# Generated by Django 3.1.5 on 2021-01-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(max_length=200)),
                ('itemCondition', models.CharField(max_length=200)),
                ('price', models.FloatField(max_length=200)),
                ('priceCurrency', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('brand', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=900)),
                ('depth', models.CharField(max_length=400)),
                ('gtin12', models.CharField(max_length=200)),
                ('logo', models.URLField(max_length=900)),
                ('manufacturer', models.CharField(max_length=900)),
                ('mpn', models.CharField(max_length=900)),
                ('sku', models.CharField(max_length=900)),
                ('alternateName', models.CharField(max_length=900)),
                ('description', models.CharField(max_length=900)),
                ('image', models.URLField(max_length=900)),
                ('name', models.CharField(max_length=900)),
            ],
        ),
    ]
